### ISSUE TITLE
nw.js (node-webkit) got MediaStreamError

### ISSUE THREAD

**Issue by xenyou** [HenrikJoreteg/getUserMedia#7]
nw.js (node-webkit) uses file:// protocol. So this commit triggers the error.
Why is this not supported?

https://github.com/HenrikJoreteg/getUserMedia/commit/1621f3108e2a70dd099dac42d9707eb6caaed3c7

**Comment by SeyZ** [comment]
:+1: for the question

@legastero ?

**Comment by SeyZ** [comment]
Pull Request available: https://github.com/HenrikJoreteg/getUserMedia/pull/8

**Comment by maxogden** [comment]
+1, this issue also makes this module unusable in atom-shell

**Comment by legastero** [comment]
We've filed a bug for Chrome about the issue (it shows no prompt and gives no error when calling from a `file://` URI).

The protocol check has been removed in `1.2.1`.
